# FROM node:16.6-alpine

# ENV PYTHONUNBUFFERED=1
# RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
# RUN python3 -m ensurepip
# RUN pip3 install --no-cache --upgrade pip setuptools


FROM node:10
RUN yarn global add bs-platform

RUN yarn global add bs-platform