export const restaurantCategories: string[] = 
[
    "Afghan", 
    "African",
    "Alcohol",
    "American",
    "Arabian",
    "Argentinian",
    "Asian Fusion",
    "Asian",
    "Australian",
    "Bakery",
    "Bar Food",
    "BBQ",
    "Belgian",
    "Biryani",
    "Brazilian",
    "Breakfast and Brunch",
    "British",
    "Bubble Tea",
    "Burgers",
    "Burmese",
    "Cafe",
    "Cajun",
    "Cantonese",
    "Caribbean",
    "Chicken",
    "Chinese",
    "Coffee and Tea",
    "Colombian",
    "Comfort Food",
    "Congee",
    "Cuban",
    "Cupcakes",
    "Curry",
    "Czech",
    "Danish",
    "Deli",
    "Desserts",
    "Diner",
    "Dominican",
    "Donuts",
    "Dosa",
    "Eastern European",
    "Egyptian",
    "English",
    "Ethiopian",
    "European",
    "Family Meals",
    "Fast Food",
    "Filipino",
    "Fish and Chips",
    "French",
    "Georgian",
    "German",
    "Gluten Free",
    "Gourmet",
    "Greek",
    "Grocery",
    "Halal",
    "Hawaiian",
    "Healthy",
    "Himalayan",
    "Ice Cream + Frozen Yogurt",
    "Indian Curry",
    "Indian",
    "Indonesian",
    "Iranian",
    "Irish",
    "Italian",
    "Jamaican",
    "Japanese BBQ",
    "Japanese",
    "Japanese Style crurry",
    "Jewish",
    "Juice and Smoothies",
    "Kids Friendly",
    "Korean",
    "Kosher",
    "Laotian",
    "Latin American",
    "Latin Fusion",
    "Lebanese",
    "Malaysian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Modern European",
    "Modern French",
    "Moroccan",
    "Nepalese",
    "New American",
    "New Mexican",
    "North Indian",
    "Northeastern Thai",
    "Northern Thai",
    "Pakistani",
    "Paleo",
    "Pasta",
    "Pastry",
    "Persian",
    "Peruvian",
    "Pharmacy",
    "Pie",
    "Pizza",
    "Poke",
    "Polish",
    "Portuguese",
    "Pub",
    "Ramen",
    "Rolls",
    "Russian",
    "Salads",
    "Salvadorian",
    "Sandwiches",
    "Seafood",
    "Shawarma",
    "Singaporean",
    "Soul Food",
    "Soup",
    "South African",
    "South American",
    "South Asian",
    "South Indian",
    "Southern",
    "Southern Thai",
    "Spanish",
    "Street Food",
    "Sushi",
    "Swedish",
    "Taiwanese",
    "Tex Mex",
    "Thai",
    "Traditional American",
    "Turkish",
    "Ukrainian",
    "Vegan Friendly",
    "Vegan",
    "Vegetarian Friendly",
    "Vegetarian",
    "Venezuelan",
    "Vietnamese",
    "West African",
    "West Indian",
    "Western",
    "Wings",
    "Wraps",
    "Yakitori",
    "Yucatecan"
]