/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UzgpuHlrX",
    "aws_user_pools_web_client_id": "2qfe95j05m6rek8fu1f1ucpea",
    "oauth": {}
};


export default awsmobile;
