import React, { useState, useEffect } from 'react';

import { createStyles, makeStyles, ThemeProvider } from '@mui/styles';
import { Theme } from '@mui/material';
import Modal from '@mui/material/Modal';

const useStyles = makeStyles((theme: Theme) => (
    createStyles({
        root: {
            backgroundColor: '#FFFFFF',
            flexGrow: 1,
            display: 'flex',
            flexDirection: 'column',
            minHeight: '100vh',

        },
        DataGrid: {
            backgroundColor: '#E0E0E0',
        },
        Modal: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
        },
    })
));

const WritingPage: React.FC = () => {
    useEffect(() => {
    }, [])
    const [isLoading, setIsLoading] = useState<boolean>(true)
    const classes = useStyles()

    return (
        <div>
            <h1 id="decentralised-websites-and-web-3-0">Decentralised websites and Web 3.0</h1>
            <h2 id="a-quick-rundown-of-web-1-2-3">A quick rundown of web 1, 2 &amp; 3</h2>
            <p>Web1</p>
            <ul>
                <li>The web was readonly. Everything was decentralised because everyone was hosting their own websites </li>
            </ul>
            <p>Web2</p>
            <ul>
                <li>The web is read &amp; write - we now need servers! Centralised everything into cloud platforms (AWS, Azure etc.). Cloud platorms won the competetive-driven pricing game through economies of scale. They attracted consumers because everyone hates running servers and platforms can provide services ontop of servers</li>
            </ul>
            <p>Web3</p>
            <ul>
                <li>Aims to cover some of the functionality of web 2 but in a decentralised manner</li>
            </ul>
            <h2 id="key-players-in-a-web2-website">Key players in a web2 website</h2>
            <h3 id="static-files">Static files</h3>
            <p>Files (html, js, css) which are stored in a cloud environmet</p>
            <h3 id="cloud-services-authentication-api-s-databases-etc-">Cloud services (authentication, api&#39;s, databases, etc)</h3>
            <p>The website will connect to the creators cloud environment and also 3rd party cloud environments to provide functionality for the website.</p>
            <h3 id="decentralised-services-crypto-defi-dao-s-">Decentralised services (crypto, DeFi, DAO&#39;s)</h3>
            <h3 id="a-domain">A domain</h3>
            <p>Purchased and payed for yearly through a domain registrar. The information relating to this domain is stored and managed by ICANN - a non profit in the USA. ICANN allocates ip address space and manages DNS for the internet.</p>
            <h2 id="key-players-in-a-web3-website-and-how-they-re-different">Key players in a web3 website and how they&#39;re different</h2>
            <h3 id="static-files">Static files</h3>
            <p>Files (html, js, css) which are stored on IPFS - a peer to peer decetralised storage network. Instead of fetching files on location it fetches based on this thing called a content address. </p>
            <p>A content address hash is generated by the file content and is unique</p>
            <p>The files themselves are stored across various peers on the network and are fetched via IPFS given the content address hash.</p>
            <h3 id="cloud-services-authentication-api-s-databases-etc-">Cloud services (authentication, api&#39;s, databases, etc)</h3>
            <h3 id="decentralised-services-crypto-defi-dao-s-">Decentralised services (crypto, DeFi, DAO&#39;s)</h3>
            <h3 id="a-nft-domain">A NFT domain</h3>
            <p>Your domain is an NFT which you personally own in a digital wallet on a cryptocurreny network. It is verifiebly unique via a blockchain. </p>
            <p>Host websites, receive crypto, login to web3 apps.</p>
            <p>Because you personally own your domain this eliminates the risk of ICANN&#39;s servers being hacked, domains being stolen or government intervention. </p>
            <h2 id="challenges-of-web3">Challenges of Web3</h2>
            <p>Incentives drive things towards centralisation</p>
            <p>User experience is terrible</p>
            <p>Developer experience is terrible</p>

        </div>
    );
}

export default WritingPage;